version: '2.1'
services:
  postgres:
    image: postgres
    restart: always
    container_name: dr.office-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

  dr.office:
    build: .
    container_name: dr.office-app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - db_network

networks:
  db_network:
    driver: bridge