version: '2.1'
services:
  dr.office:
    build: .
    image: dr.office
    container_name: dr.office
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PATH=${DB_PATH}
    ports:
      - 5000:8000
  dr.office-e2e:
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile
    image: dr.office-e2e
    container_name: dr.office-e2e
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_PATH=${DB_PATH}
    ports:
      - 5002:8000