version: '2.1'
services:
  dr.office:
    build: .
    container_name: dr.office
    environment:
      - PYTHONUNBUFFERED=1
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_USERNAME=${JWT_USERNAME}
      - JWT_PASSWORD=${JWT_PASSWORD}
      - DB_PATH=${DB_PATH}
    ports:
      - 5000:8000